version: "3.9"
services:
  backend:
    build: ./backend
    container_name: thoughtloop_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data  # データベースファイルを永続化
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./frontend
    container_name: thoughtloop_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
